version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      # - /app/node_modules # Used to not sync local and container node_modules
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./db-data:/app/db-data

volumes:
  db-data:
